apps/waste_generators/urls.py
from django.urls import path
from . import views
from apps.waste_generators.pickup_views import (
    waste_pickup_dashboard, 
    waste_pickup_form_view, 
    submit_waste_pickup,
    get_pickup_food_type,
    waste_Pickups_import,
    waste_Pickups_download_template,
    download_template,
    upload_excel,
    save_mapped_data,
    download_temp_getting_names,
    edit_pickup_view,
    update_pickup,
    delete_pickups
)

app_name = "generators"

urlpatterns = [
    path("dashboard/", views.generator_dashboard_view, name="waste_generator_dashboard"),
    path("edit/<int:pk>/", views.generator_form_edit_view, name="edit_generator"),

    path("add/", views.generator_form_view, name="add_generator"),
    path("save/", views.save_generator, name="save_generator"),

    #PICKUPS
    path("pickup/dashboard/", waste_pickup_dashboard, name="waste_pickup_dashboard"),
    path("pickup/form/", waste_pickup_form_view, name="waste_pickup_form"),
    path("pickup/submit/", submit_waste_pickup, name="submit_waste_pickup"),
    path("get/food_type/<int:group_id>/", get_pickup_food_type, name="get_pickup_food_type"),
    path('edit_pickup_view/<int:pickup_id>/', edit_pickup_view, name='edit_pickup_view'),
    path('update/', update_pickup, name='update_pickup'),
    path("delete/", delete_pickups, name="delete_pickups"),



    # Import 
    path('waste_Pickups_import/', waste_Pickups_import, name='waste_Pickups_import'),
    path('waste_Pickups_download_template/', waste_Pickups_download_template, name='waste_Pickups_download_template'),

    # Import and download template 
    path('download-template/', download_template, name='download_template'),
    path('upload_excel', upload_excel, name='upload_excel'),
    path('save_mapped_data', save_mapped_data, name='save_mapped_data'),
    path('download_temp_getting_names', download_temp_getting_names, name='download_temp_getting_names'),
    

]

reuse_track/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework import permissions
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView
)
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', include('apps.users.api_urls')),

    # Schema generation endpoint
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),

    # Swagger UI
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

    # Redoc UI (optional)
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    path('', lambda request: redirect('/dashboard')),

    path('', include('apps.users.api_urls')),
    path('', include('apps.common.urls')),
    path("agreements/", include("apps.agreements.urls")),
    path("generators/", include("apps.waste_generators.urls", namespace="generators")),
    path("collectors/", include("apps.waste_collectors.urls", namespace="collectors")),
    path("commodities/", include("apps.core.urls", namespace="core")),
    path("audits/", include("apps.audits.urls")),
    path("waste/", include("apps.waste_source_group.urls", namespace="waste_source_group")),
    path('client/commodities/', include("apps.commodities.urls", namespace="commodities"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/waste_generators/models.py
from django.db import models
from apps.common.models import TimeStampedModel
from apps.users.models import User
from apps.waste_source_group.models import WasteGroupMaster, WasteGeneratorGroup, MasterSource, MasterDestination
from apps.core.models import CommodityGroup
from apps.common.models import Address
from apps.core.models import CommodityMater

class WasteSourceMaster(TimeStampedModel):
    waste_source = models.ForeignKey(MasterSource, on_delete=models.CASCADE)
    STATUS_CHOICES = [
        ('A', 'Active'),
        ('I', 'Inactive'),
    ]
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='A')
    waste_group = models.ForeignKey(WasteGeneratorGroup, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, blank=True)
    contact_name = models.CharField(max_length=255, blank=True, null=True)
    contact_phone = models.CharField(max_length=15, blank=True, null=True)
    contact_email = models.EmailField(null=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.waste_source.name

class WasteSourceSpecificationMaster(models.Model):
    waste_source = models.ForeignKey(WasteSourceMaster, on_delete=models.CASCADE)
    specification = models.CharField(max_length=255)

    STATUS_CHOICES = [
        ('A', 'Active'),
        ('I', 'Inactive'),
    ]
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='A')

    def __str__(self):
        return f"{self.waste_source} - {self.specification}"

class Generator(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    address_line_1 = models.CharField(max_length=255, blank=True, null=True)
    address_line_2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    pin_code = models.CharField(max_length=20, blank=True, null=True)

    waste_source = models.ForeignKey(WasteSourceMaster, on_delete=models.CASCADE, null=True)
    waste_source_specification =  models.ForeignKey(WasteSourceSpecificationMaster, on_delete=models.CASCADE, null=True)
    Waste_generator_group = models.ForeignKey(WasteGeneratorGroup, on_delete=models.CASCADE, null=True)

    contact_name = models.CharField(max_length=255, blank=True, null=True)
    contact_phone = models.CharField(max_length=15, blank=True, null=True)
    contact_email = models.EmailField(null=True)

    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class WasteSource(TimeStampedModel):
    waste_source = models.ForeignKey(MasterSource, on_delete=models.CASCADE)
    waste_type = models.ForeignKey(CommodityGroup, on_delete=models.CASCADE)
    food_type = models.ForeignKey(CommodityMater, on_delete=models.CASCADE)
    waste_weight = models.FloatField()

    def __str__(self):
        return f"{self.waste_source.name} - {self.food_type} ({self.waste_weight}kg)"
    
class WastePickUp(TimeStampedModel):
    from apps.waste_collectors.models import Collector

    pickup_date = models.DateField()
    waste_source = models.ForeignKey(WasteSource, on_delete=models.CASCADE)
    address = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField(upload_to='waste_pickup', blank=True, null=True)
    destination = models.ForeignKey(Collector, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.pickup_date} at {self.address}"

apps/waste_generators/views.py
from django.shortcuts import render
from django.db.models import Q
from apps.waste_generators.models import (
    Generator,
    WasteSourceMaster, 
    WasteSourceSpecificationMaster
)
from apps.waste_source_group.models import WasteGroupMaster, WasteGeneratorGroup
from apps.waste_generators.services import GeneratorService
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

@login_required(login_url='login')
def generator_dashboard_view(request):
    query = request.GET.get("q", "")
    generators = GeneratorService.search_generators(query)
    return render(request, "generators/waste-generator-dashboard.html", {"generators": generators})


@login_required(login_url='login')
def generator_form_edit_view(request, pk=None):
    is_edit = pk is not None
    generator = get_object_or_404(Generator, pk=pk) if is_edit else None

    context = {
        "waste_groups": WasteGeneratorGroup.objects.all(),
        "sources": WasteSourceMaster.objects.all(),
        "specifications": WasteSourceSpecificationMaster.objects.all(),
        "generator": generator,
        "is_edit": is_edit,
        "page_title": "Edit Waste Generator" if is_edit else "Add Waste Generator"
    }
    return render(request, "generators/waste-generator-form.html", context)

@login_required(login_url='login')
def generator_form_view(request):
    context = {
        "waste_groups": WasteGeneratorGroup.objects.all()
    }
    return render(request, "generators/waste-generator-form.html", context)


def save_generator(request):
    if request.method == "POST":
        return GeneratorService.handle_submission(request)
    return JsonResponse({"success": False, "message": "Invalid request"}, status=400)

apps/waste_generators/templates/generators/waste-generator-dashboard.html
{% extends "base.html" %}
{% load static %}

{% block title %}Waste Generator Dashboard{% endblock %}
{% block extra_css %}{% endblock %}
{% block body_id %}dashboard{% endblock %}

{% block content %}
<div class="off-canvas-content" data-off-canvas-content>
    {% include "includes/sidebar_router.html" with active_page="waste_generator_dashboard" %}
    <div class="grid-x">
        <div class="cell large-10 large-offset-2">
            {% include 'partials/header_authenticated.html' with page_name="Waste Generator Dashboard" %}
            <div class="dashboard-content">
                <div class="table-container">
                    <div class="grid-x">
                        <div class="cell large-12">
                            <div class="callout">
                                <div class="dashboard-callout">
                                    <div class="grid-x grid-margin-y small-up-1 medium-up-2">
                                        <div class="cell">
                                            <span class="sub-title">Waste Generators</span>
                                        </div>
                                        <div class="cell">
                                            <form method="get">
                                                <input type="search" name="q" value="{{ request.GET.q }}" placeholder="Search" class="pill float-right" style="width: 50%; padding: 0.5rem;">
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="table">
                                    <table class="stack">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Waste Generator Name</th>
                                                <th>Waste Generator Address</th>
                                                <th>Waste Generator Group</th>
                                                <th>Contact Name</th>
                                                <th>Contact Phone</th>
                                                <th>Contact Email</th>
                                                <th>Waste Generator Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for generator in generators %}
                                            <tr>
                                                <td><a href="{% url 'generators:edit_generator' generator.id %}">{{ generator.id }}</a></td>
                                                <td>{{ generator.name }}</td>
                                                <td>{% if generator.address_line_1 %} {{ generator.address_line_1 }}, {{generator.city}}, {{generator.pin_code}} {% else %}-{% endif %}</td>
                                                <td>{{generator.Waste_generator_group.name}}</td>
                                                <td>{% if generator.contact_name %} {{ generator.contact_name }} {% else %}-{% endif %}</td>
                                                <td>{% if generator.contact_phone %} {{ generator.contact_phone }} {% else %}-{% endif %}</td>
                                                <td>{% if generator.contact_email %} {{ generator.contact_email }} {% else %}-{% endif %}</td>
                                                <td>{% if generator.is_active %} Active {% else %} Inactive {% endif %}</td>
                                            </tr>
                                            {% empty %}
                                            <tr>
                                                <td colspan="9" class="text-center">No generators found.</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
             </div>
        </div>
    </div>
</div>
{% endblock %}

apps/waste_generators/templates/generators/waste-generator-form.html
{% extends "base.html" %}
{% load static %}

{% block title %}Add Waste Generator{% endblock %}
{% block body_id %}dashboard{% endblock %}
{% block content %}
<div class="off-canvas-content" data-off-canvas-content>
    {% include "includes/sidebar_router.html" with active_page="waste_generator_dashboard" %}
    <div class="grid-x">
        <div class="cell large-10 large-offset-2">
            {% include 'partials/header_authenticated.html' with page_name='Add Waste Generator' %}
            <div class="dashboard-content">
                <div class="grid-container">
                    <div class="grid-x">
                        <div class="cell large-7 grid-center">
                            <div class="callout">
                                <form id="generator-form" method="POST">
                                    {% csrf_token %}
                                    <div class="grid-x">
                                        <input type="hidden" name="id" value="{{ generator.id|default:'' }}">

                                        <div class="cell">
                                            <label>Waste Generator Name</label>
                                            <input type="text" name="waste_generator_name" required value="{{ generator.name|default:'' }}">
                                        </div>

                                        <div class="cell">
                                            <label>Waste Generator Address</label>
                                            <div class="grid-x grid-margin-x">
                                                <div class="cell small-6">
                                                    <input type="text" name="address_one" placeholder="Address 1" required required value="{{ generator.address_line_1|default:'' }}">
                                                </div>
                                                <div class="cell small-6">
                                                    <input type="text" name="address_two" placeholder="Address 2" value="{{ generator.address_line_2|default:'' }}">
                                                </div>
                                                <div class="cell small-6">
                                                    <input type="text" name="city" placeholder="City" required value="{{ generator.city|default:'' }}">
                                                </div>
                                                <div class="cell small-6">
                                                    <input type="text" name="state" placeholder="State" required value="{{ generator.state|default:'' }}">
                                                </div>
                                                <div class="cell small-6">
                                                    <input type="text" name="zipcode" placeholder="Zipcode" required value="{{ generator.pin_code|default:'' }}">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="cell">
                                            <label>Waste Generator Group</label>
                                            <select name="waste_group" required>
                                                <option value="">Select Group</option>
                                                {% for waste_group in waste_groups %}
                                                    <option value="{{waste_group.id}}" {% if generator.Waste_generator_group.id == waste_group.id %}selected{% endif %}>{{waste_group.name}}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="cell">
                                            <label>Contact Name</label>
                                            <input type="text" name="contact_name" required value="{{ generator.contact_name|default:'' }}">
                                        </div>

                                        <div class="cell">
                                            <label>Contact Phone No</label>
                                            <input type="tel" name="contact_phone" required pattern="^\d{10}$" value="{{ generator.contact_phone|default:'' }}">
                                        </div>

                                        <div class="cell">
                                            <label>Contact Email</label>
                                            <input type="email" name="contact_email" required value="{{ generator.contact_email|default:'' }}">
                                        </div>

                                        <div class="cell">
                                            <label>Waste Generator Status</label>
                                            <input type="checkbox" name="waste_generator_status" {% if generator.is_active %}checked{% endif %}> Active
                                        </div>
                                    </div>

                                    <div class="grid-x">
                                        <div class="cell">
                                            <div class="button-group expanded">
                                                <button type="submit" class="button pill">Submit</button>
                                            </div>
                                        </div>
                                    </div>

                                    <div id="error-box" class="callout alert" style="display:none;"></div>
                                    <div id="success-box" class="callout success" style="display:none;"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script>
document.getElementById("generator-form").addEventListener("submit", function (e) {
    e.preventDefault();

    const form = e.target;
    const generatorId = form.getAttribute('data-id');
    const url = "{% url 'generators:save_generator' %}";
    const data = new FormData(form);
    const successBox = document.getElementById("success-box");
    const errorBox = document.getElementById("error-box");

    fetch(url, {
        method: "POST",
        headers: { "X-CSRFToken": document.querySelector('[name=csrfmiddlewaretoken]').value },
        body: data,
    })
    .then(res => res.json())
    .then(data => {
        if (data.success) {
            successBox.innerText = "Generator added successfully!";
            successBox.style.display = "block";
            errorBox.style.display = "none";
            form.reset();
            Swal.fire({
                icon: 'success',
                title: 'Success!',
                text: 'Added waste generator successfully.',
                confirmButtonText: 'OK',
                allowOutsideClick: false,     // Prevent click outside
                allowEscapeKey: false,        // Prevent ESC key
                allowEnterKey: true           // Optional: allow Enter to confirm
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = '/generators/dashboard/';
                }
            });
        } else {
            errorBox.innerText = data.message || "Something went wrong!";
            errorBox.style.display = "block";
            successBox.style.display = "none";
        }
    })
    .catch(() => {
        errorBox.innerText = "Server error.";
        errorBox.style.display = "block";
    });
});
</script>
{% endblock %}