apps/agreements/urls.py
from django.urls import path
from apps.agreements.views import (
    agreement_dashboard_view, 
    agreement_form_view, 
    agreement_ajax_submit,
    agreement_edit_form,
    agreement_ajax_update,
    delete_agreements
)

app_name = 'agreements'

urlpatterns = [
    path("dashboard/", agreement_dashboard_view, name="dashboard"),
    path("form/", agreement_form_view, name="form"),
    path("ajax-submit/", agreement_ajax_submit, name="ajax_submit"),

    path("edit/<int:id>/", agreement_edit_form, name="edit_form"),
    path("ajax-submit/", agreement_ajax_submit, name="ajax_submit"),
    path("update/", agreement_ajax_update, name="agreement_ajax_update"),
    path("delete/", delete_agreements, name="delete_agreements"),
]

apps/audits/urls.py
from django.urls import path
from apps.audits.views.audit_views import audit_dashboard_view
from apps.audits.views.audit_schedule import schedule_audit_form_view, schedule_audit_submit, get_addresses_by_locations
from apps.audits.views.audit_add import audit_form_view, audit_form_submit
from apps.audits.views.audit_report import audit_report_view

app_name = "audits"

urlpatterns = [
    path("dashboard/", audit_dashboard_view, name="dashboard"),

    # Lambda views for temporary usage
    path("audits/report/<int:audit_id>/", audit_report_view, name="audit_report"),
    path('audits/add/<int:audit_id>/', audit_form_view, name='add_audit'),

    path('audit/schedule/', schedule_audit_form_view, name='audit_schedule_form'),
    path('audit/schedule/submit/', schedule_audit_submit, name='audit_schedule_submit'),
    path('get-addresses/', get_addresses_by_locations, name='get_addresses_by_locations'),

    # path("add/audit/", audit_form_view, name="add_audit"),
    path("submit/audit/", audit_form_submit, name="submit_audit"),
]

apps/common/urls.py
# apps/dashboard/urls.py

from django.urls import path
from apps.common.views import dashboard_view
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "dashboard"

urlpatterns = [
    path("dashboard", dashboard_view, name="dashboard"),  # Accessible via /dashboard/
    path('dashboard/data-manager/', views.data_manager_dashboard, name="data_manager"),
    path('dashboard/auditor/', views.auditor_dashboard, name="auditor"),
    path('dashboard/city-admin/', views.city_admin_dashboard, name="city_admin"),
    path("dashboard/universal/", views.universal_dashboard, name="dashboard_universal"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/core/urls.py
from django.urls import path
from apps.core.views import (
    master_commodity_dashboard, 
    commodity_form_view, 
    add_commodity_ajax,
    upload_commodity_document,
    unit_form_view,
    add_unit_ajax,
    edit_commodity_view,
    update_commodity,
    commodity_bulk_import_view,
    upload_excel,
    add_commodities_form,
    commodities_type_dashboard,
    create_commodity_type,
    edit_commodity_type_page,
    edit_commodity_type,
    delete_commodities
)
from apps.core.bulk_upload_view import bulk_upload_commodity_data

app_name = "core"

urlpatterns = [
    path("dashboard/", master_commodity_dashboard, name="dashboard"),
    path('edit/<int:id>/', edit_commodity_view, name='edit_commodity'),
    path('update/', update_commodity, name='update_commodity'),
    path('delete/', delete_commodities, name='delete_commodities'),


    path("add/", commodity_form_view, name="commondity_form"),
    path("add/submit/", add_commodity_ajax, name="add_commodities"),
    path("upload-document/", upload_commodity_document, name="upload_doc_commoditi"),
    path("unit/form/", unit_form_view, name="unit_form"),
    path("unit/add/", add_unit_ajax, name="add_unit"),

    path("commodity/bulk-import/", commodity_bulk_import_view, name="commodity_bulk_import_view"),
    path('upload_excel/',upload_excel,name='upload_excel'),
    path('save_mapped_data/', bulk_upload_commodity_data, name='save_mapped_data'),

    path('add/type/', add_commodities_form, name="add_commodities_type"),
    path('type/dashboard/', commodities_type_dashboard, name="commodities_type_dashboard"),
    path('create/type/', create_commodity_type, name='create_commodity_type'),
    path('edit/type/<int:pk>/', edit_commodity_type, name='edit_commodity_type'),
    path('edit/type/page/<int:pk>/', edit_commodity_type_page, name='edit_commodity_type_page'),
]

reuse_track/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework import permissions
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView
)
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', include('apps.users.api_urls')),

    # Schema generation endpoint
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),

    # Swagger UI
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

    # Redoc UI (optional)
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    path('', lambda request: redirect('/dashboard')),

    path('', include('apps.users.api_urls')),
    path('', include('apps.common.urls')),
    path("agreements/", include("apps.agreements.urls")),
    path("generators/", include("apps.waste_generators.urls", namespace="generators")),
    path("collectors/", include("apps.waste_collectors.urls", namespace="collectors")),
    path("commodities/", include("apps.core.urls", namespace="core")),
    path("audits/", include("apps.audits.urls")),
    path("waste/", include("apps.waste_source_group.urls", namespace="waste_source_group")),
    path('client/commodities/', include("apps.commodities.urls", namespace="commodities"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Tracker{% endblock %}</title>
    <link rel="icon" href="{% static 'images/water-bottle.png' %}" type="image/x-icon">

    <!-- Global styles -->
    <link rel="stylesheet" href="{% static 'vendors/fontawesome/css/all.min.css' %}"/>

    <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">

    <link rel="stylesheet" href="{% static 'foundation-icons/foundation-icons.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <!-- SweetAlert2 CSS -->
    <link rel="stylesheet" href="{% static 'vendors/sweetalert2/sweetalert2.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/select2/select2.min.css' %}">

    <!-- Page-specific CSS -->
    {% block extra_css %}{% endblock %}
</head>
<body id="{% block body_id %}{% endblock %}">
    
    <div class="off-canvas-wrapper">
        <div class="off-canvas position-left" id="offCanvas" data-off-canvas>
            <!-- Your menu or Off-canvas content goes here -->
        </div>
        {% block content %}{% endblock %}
    </main>

    {% include "partials/footer.html" %}

    <!-- Global JS -->
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>

    <script src="{% static 'js/scrollfade-0.1.js' %}"></script>

    <!-- SweetAlert2 JS -->
    <script src="{% static 'vendors/sweetalert2/sweetalert2.js' %}"></script>
    <script src="{% static 'vendors/select2/select2.min.js' %}"></script>
    
    <!-- Page-specific JS -->
    {% block extra_js %}{% endblock %}
</body>
</html>

templates/side_bar.html
{% load static %}
<div class="callout side-bar show-for-large">
    <div class="side-nav">
        <ul class="menu vertical">
            <li class="logo-mark"><a href=""></a></li>
            <li><a href="#" style="background: url(/static/images/iconmonstr-paper-plane-2.png) no-repeat center;"></a>
            </li>
            <li><a href="#" style="background: url(/static/images/iconmonstr-note-38.png) no-repeat center;"></a></li>
            <li><a href="#" style="background: url(/static/images/iconmonstr-help-3.png) no-repeat center;"></a></li>
        </ul>
    </div>
    <ul class="menu vertical">
        <a href="{% url 'dashboard:dashboard' %}">
            <li class="logo" style="background: url('{{ logo_url }}') no-repeat center;"></li>
        </a>
        {% if active_page == 'agreement_dashboard' %}
        <li class="{% if request.path == '/agreements/dashboard/' %}selected{% endif %}">
            <a href="{% url 'agreements:dashboard' %}">Agreement Dashboard</a>
        </li>
        <li class="{% if request.path == '/agreements/form/' %}selected{% endif %}">
            <a href="{% url 'agreements:form' %}" style="background: url() no-repeat 1px center">Add Agreement</a>
        </li>
        {% elif active_page == 'Dashboard' %}
        <li class="selected">
            <a href="#">{{ active_page }}</a>
        </li>
        <li>
            <a href="#" style="background: url() no-repeat 1px center">Locations & Buildings</a>
        </li>
        <li>
            <a href="#" style="background: url('{% static "icons/reports.png" %}') no-repeat 1px center">Reports</a>
        </li>
        <li>
            <a href="#"
                style="background: url('{% static "icons/compliance.png" %}') no-repeat 1px center">Compliance</a>
        </li>
        <li>
            <a href="{% url 'dashboard_usermanagement' %}"
                style="background: url('{% static "icons/user.png" %}') no-repeat 1px center">User Management</a>
        </li>
        <li>
            <a href="{% url 'generators:waste_generator_dashboard' %}"
                style="background: url('{% static "icons/generator.png" %}') no-repeat 1px center">Manage Waste
                Generator</a>
        </li>
        <li>
            <a href="{% url 'collectors:waste_collector_dashboard' %}"
                style="background: url('{% static "icons/collector.png" %}') no-repeat 1px center">Manage Waste
                Collector</a>
        </li>
        <li>
            <a href="{% url 'agreements:dashboard' %}"
                style="background: url('{% static "icons/agreement.png" %}') no-repeat 1px center">Manage Agreement</a>
        </li>
        <li><a href="{% url 'commodities:client_commoditi_dashboard' %}"
                style="background: url() no-repeat 1px center">Manage Commodity</a>
        </li>
        <li>
            <a href="{% url 'waste_source_group:waste_group_master_dashboard' %}"
                style="background: url() no-repeat 1px center">Manage Waste Group & <br /> Source Master</a>
        </li>
        <li>
            <a href="{% url 'core:dashboard' %}"
                style="background: url('{% static "icons/commodity.png" %}') no-repeat 1px center">Master Commodity</a>
        </li>
        <li>
            <a href="{% url 'audits:dashboard' %}"
                style="background: url('{% static "icons/audit.png" %}') no-repeat 1px center">Manage Audit</a>
        </li>
        {% elif active_page == 'user_dashboard' %}
        <li class="{% if request.path == '/dashboard/usermanagement/' %}selected{% endif %}">
            <a href="{% url 'dashboard_usermanagement' %}" style="background: url() no-repeat 1px center">User
                Dashboard</a>
        </li>

        <li class="{% if request.path == '/roles/form/' %}selected{% endif %}">
            <a href="{% url 'role_form' %}" style="background: url() no-repeat 1px center">Add Roles</a>
        </li>

        <li class="{% if request.path == '/user/add/form/' %}selected{% endif %}">
            <a href="{% url 'user_add_form' %}" style="background: url() no-repeat 1px center">Add User</a>
        </li>

        <li class="{% if request.path == '/user-roles/' %}selected{% endif %}">
            <a href="{% url 'dashboard_userroles' %}" style="background: url() no-repeat 1px center">Manage Roles</a>
        </li>
        <li class="{% if request.path == '/permissions/form/' %}selected{% endif %}">
            <a href="{%url 'permission_form' %}" style="background: url() no-repeat 1px center">Manage Permission</a>
        </li>
        {% elif active_page == 'commodities' %}
        <li class="{% if request.path == '/commodities/dashboard/' %}selected{% endif %}">
            <a href="{% url 'core:dashboard' %}" style="background: url() no-repeat 1px center">
                Commodity dashboard
            </a>
        </li>

        <li class="{% if request.path == '/commodities/add/type/' %}selected{% endif %}">
            <a href="{% url 'core:add_commodities_type' %}" style="background: url() no-repeat 1px center">
                Add Commodity Type
            </a>
        </li>

        <li class="{% if request.path == '/commodities/type/dashboard/' %}selected{% endif %}">
            <a href="{% url 'core:commodities_type_dashboard' %}">
                Commodity Type Dashboard
            </a>
        </li>

        <li class="{% if request.path == '/commodities/unit/form/' %}selected{% endif %}">
            <a href="{% url 'core:unit_form' %}" style="background: url() no-repeat 1px center">Unit</a>
        </li>

        <li class="{% if request.path == '/commodities/add/' %}selected{% endif %}">
            <a href="{% url 'core:commondity_form' %}" style="background: url() no-repeat 1px center">
                Add Commodity
            </a>
        </li>

        <li class="{% if request.path == '/commodities/commodity/bulk-import/' %}selected{% endif %}">
            <a href="{% url 'core:commodity_bulk_import_view' %}">Upload</a>
        </li>
        {% elif active_page == 'waste_generator_dashboard' %}
        <li class="{% if request.path == '/generators/dashboard/' %}selected{% endif %}">
            <a href="{% url 'generators:waste_generator_dashboard' %}"
                style="background: url() no-repeat 1px center">Waste Generator Dashboard</a>
        </li>
        <li class="{% if request.path == '/generators/add/' %}selected{% endif %}">
            <a href="{% url 'generators:add_generator' %}" style="background: url() no-repeat 1px center">Add Waste
                Generator</a>
        </li>
        {% elif active_page == 'waste_collector' %}
        <li class="{% if request.path == '/collectors/dashboard/' %}selected{% endif %}">
            <a href="{% url 'collectors:waste_collector_dashboard' %}">
                Waste Collector
            </a>
        </li>

        <li class="{% if request.path == '/collectors/collector_type_form_add/' %}selected{% endif %}">
            <a href="{% url 'collectors:collector_type_form_add' %}" style="background: url() no-repeat 1px center">
                Add Collector Type
            </a>
        </li>

        <li class="{% if request.path == '/collectors/add/' %}selected{% endif %}">
            <a href="{% url 'collectors:add' %}" style="background: url() no-repeat 1px center">
                Add Waste Collector
            </a>
        </li>

        <li class="{% if request.path == '/collectors/waste_collector_download_template/' %}selected{% endif %}">
            <a href="{% url 'collectors:waste_collector_download_template' %}"
                style="background: url() no-repeat 1px center">
                Download Template
            </a>
        </li>

        <li class="{% if request.path == '/collectors/waste_collector_import/' %}selected{% endif %}">
            <a href="{% url 'collectors:waste_collector_import' %}" style="background: url() no-repeat 1px center">
                Waste Collector Import
            </a>
        </li>

        {% elif active_page == 'audit' %}
        <li class="{% if request.path == '/audits/dashboard/' %}selected{% endif %}">
            <a href="{% url 'audits:dashboard' %}" style="background: url() no-repeat 1px center">Dashboard</a>
        </li>
        <li class="{% if request.path == '/audits/audit/schedule/' %}selected{% endif %}">
            <a href="{% url 'audits:audit_schedule_form' %}" style="background: url() no-repeat 1px center">Schedule
                Audit</a>
        </li>
        {% comment %} <li class="{% if request.path == '/audits/add/audit/' %}selected{% endif %}">
            <a href="{% url 'audits:add_audit' %}" style="background: url() no-repeat 1px center">Audit</a>
        </li> {% endcomment %}
        {% elif active_page == 'client_commodity' %}
        <li class="{% if request.path == '/commodities/client/dashboard/' %}selected{% endif %}">
            <a href="{% url 'core:client_commoditi_dashboard' %}" style="background: url() no-repeat 1px center">Client
                Commodity dashboard</a>
        </li>
        <li>
            <a href="client_commodity_form" style="background: url() no-repeat 1px center">Add Client Commodity</a>
        </li>
        {% elif active_page == 'waste_source' %}
        <li class="{% if request.path == '/waste/group/dashboard/' %}selected{% endif %}">
            <a href="{% url 'waste_source_group:waste_group_master_dashboard' %}"
                style="background: url() no-repeat 1px center">Waste Group Master Dashboard</a>
        </li>
        <li class="{% if request.path == '/waste/group/form/' %}selected{% endif %}">
            <a href="{% url 'waste_source_group:waste_group_master_form' %}"
                style="background: url() no-repeat 1px center">Add Waste Group Master</a>
        </li>
        <li class="{% if request.path == '/waste/source/dashboard/' %}selected{% endif %}">
            <a href="{% url 'waste_source_group:waste_source_master_dashboard' %}"
                style="background: url() no-repeat 1px center">Organic Generator Master Dashboard Dashboard</a>
        </li>
        <li class="{% if request.path == '/waste/source/form/' %}selected{% endif %}">
            <a href="{% url 'waste_source_group:waste_source_master_form' %}"
                style="background: url() no-repeat 1px center">Add Organic Generator Master Dashboard</a>
        </li>
        {% endif %}

    </ul>
    <div class="notes" style="display:none">
        <ul class="menu vertical">
            <li><a href="#" style="background: url(/static/images/makefg.png) no-repeat 0px center">Updates</a></li>
        </ul>
        <small>Donec ullamcorper nulla non metus auctor fringilla. Cras mattis consectetur purus sit amet fermentum.
            Aenean lacinia bibendum nulla sed consectetur.</small>
    </div>
</div>